<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Supplier;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suppliers = [
            [
                'name' => 'PharmaCorp India Ltd',
                'code' => 'PHAR001',
                'contact_person' => 'Dr. Rajesh Kumar',
                'email' => 'info@pharmacorp.com',
                'phone' => '+91-11-4567-8901',
                'address' => 'A-25, Industrial Area, Phase-II',
                'city' => 'New Delhi',
                'state' => 'Delhi',
                'postal_code' => '110020',
                'country' => 'India',
                'gst_number' => '07AABCP1234R1ZX',
                'license_number' => 'DL-MF-001234',
                'website' => 'https://pharmacorp.com',
                'credit_limit' => 500000.00,
                'payment_terms_days' => 30,
                'is_active' => true,
                'notes' => 'Leading pharmaceutical supplier with wide range of generic and branded medicines. Excellent track record of timely deliveries.',
            ],
            [
                'name' => 'MediSupply Solutions',
                'code' => 'MEDI002',
                'contact_person' => 'Mrs. Priya Sharma',
                'email' => 'contact@medisupply.in',
                'phone' => '+91-22-9876-5432',
                'address' => 'Plot No. 42, MIDC Industrial Estate',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'postal_code' => '400076',
                'country' => 'India',
                'gst_number' => '27AABCM5678Q1ZY',
                'license_number' => 'MH-MF-005678',
                'website' => 'https://medisupply.in',
                'credit_limit' => 750000.00,
                'payment_terms_days' => 45,
                'is_active' => true,
                'notes' => 'Specialized in surgical supplies and medical equipment. Premium quality products with competitive pricing.',
            ],
            [
                'name' => 'HealthCare Distributors',
                'code' => 'HEAL003',
                'contact_person' => 'Mr. Amit Patel',
                'email' => 'sales@healthcare-dist.com',
                'phone' => '+91-79-1234-5678',
                'address' => '15, Commerce Park, S.G. Highway',
                'city' => 'Ahmedabad',
                'state' => 'Gujarat',
                'postal_code' => '380015',
                'country' => 'India',
                'gst_number' => '24AABCH9012P1ZW',
                'license_number' => 'GU-MF-009012',
                'website' => 'https://healthcare-distributors.com',
                'credit_limit' => 300000.00,
                'payment_terms_days' => 21,
                'is_active' => true,
                'notes' => 'Fast-growing distributor focusing on diabetes care and cardiac medications. Regional coverage across Western India.',
            ],
            [
                'name' => 'BioMed Pharmaceuticals',
                'code' => 'BIOM004',
                'contact_person' => 'Dr. Sunita Reddy',
                'email' => 'info@biomed-pharma.co.in',
                'phone' => '+91-40-8765-4321',
                'address' => 'Genome Valley, Shameerpet',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'postal_code' => '500078',
                'country' => 'India',
                'gst_number' => '36AABCB3456L1ZV',
                'license_number' => 'TS-MF-003456',
                'website' => 'https://biomed-pharma.co.in',
                'credit_limit' => 1000000.00,
                'payment_terms_days' => 60,
                'is_active' => true,
                'notes' => 'Biotechnology-focused pharmaceutical company. Specializes in innovative drug formulations and research-based medicines.',
            ],
            [
                'name' => 'Generic Plus Suppliers',
                'code' => 'GENP005',
                'contact_person' => 'Mr. Ravi Krishnan',
                'email' => 'orders@genericplus.com',
                'phone' => '+91-44-5678-9012',
                'address' => 'No. 18, Anna Salai, Teynampet',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'postal_code' => '600018',
                'country' => 'India',
                'gst_number' => '33AABCG7890M1ZU',
                'license_number' => 'TN-MF-007890',
                'website' => 'https://genericplus.com',
                'credit_limit' => 400000.00,
                'payment_terms_days' => 30,
                'is_active' => true,
                'notes' => 'Exclusive focus on generic medicines with best-in-class pricing. Strong presence in South Indian markets.',
            ],
            [
                'name' => 'Metro Medical Supplies',
                'code' => 'METR006',
                'contact_person' => 'Ms. Kavita Singh',
                'email' => 'procurement@metromedical.in',
                'phone' => '+91-80-3456-7890',
                'address' => 'Electronic City, Phase-I',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'postal_code' => '560100',
                'country' => 'India',
                'gst_number' => '29AABCM2345N1ZT',
                'license_number' => 'KA-MF-002345',
                'website' => 'https://metromedical.in',
                'credit_limit' => 600000.00,
                'payment_terms_days' => 45,
                'is_active' => true,
                'notes' => 'Technology-driven medical supply chain with real-time inventory tracking. Excellent customer service and support.',
            ],
            [
                'name' => 'Wellness Pharmaceuticals',
                'code' => 'WELL007',
                'contact_person' => 'Dr. Manish Agarwal',
                'email' => 'support@wellness-pharma.com',
                'phone' => '+91-33-7890-1234',
                'address' => 'Salt Lake City, Sector-V',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'postal_code' => '700091',
                'country' => 'India',
                'gst_number' => '19AABCW4567O1ZS',
                'license_number' => 'WB-MF-004567',
                'website' => 'https://wellness-pharma.com',
                'credit_limit' => 350000.00,
                'payment_terms_days' => 30,
                'is_active' => true,
                'notes' => 'Focused on wellness and preventive healthcare products. Strong portfolio of vitamins, supplements, and OTC medicines.',
            ],
            [
                'name' => 'Global Pharma Network',
                'code' => 'GLOB008',
                'contact_person' => 'Mr. Suresh Gupta',
                'email' => 'sales@globalpharma.net',
                'phone' => '+91-172-234-5678',
                'address' => 'Industrial Area, Phase-I',
                'city' => 'Chandigarh',
                'state' => 'Punjab',
                'postal_code' => '160002',
                'country' => 'India',
                'gst_number' => '03AABCG8901P1ZR',
                'license_number' => 'PB-MF-008901',
                'website' => 'https://globalpharma.net',
                'credit_limit' => 800000.00,
                'payment_terms_days' => 60,
                'is_active' => true,
                'notes' => 'International pharmaceutical network with global sourcing capabilities. Specializes in rare and imported medicines.',
            ],
            [
                'name' => 'Essential Drugs Co.',
                'code' => 'ESSE009',
                'contact_person' => 'Mrs. Deepa Nair',
                'email' => 'info@essentialdrugs.co.in',
                'phone' => '+91-484-567-8901',
                'address' => 'Infopark, Kakkanad',
                'city' => 'Kochi',
                'state' => 'Kerala',
                'postal_code' => '682030',
                'country' => 'India',
                'gst_number' => '32AABCE5678Q1ZQ',
                'license_number' => 'KL-MF-005678',
                'website' => 'https://essentialdrugs.co.in',
                'credit_limit' => 250000.00,
                'payment_terms_days' => 15,
                'is_active' => true,
                'notes' => 'Government-approved supplier for essential drugs program. Reliable source for basic healthcare medications.',
            ],
            [
                'name' => 'PharmaLink Solutions',
                'code' => 'PHAL010',
                'contact_person' => 'Mr. Vikash Jha',
                'email' => 'connect@pharmalink.in',
                'phone' => '+91-651-890-1234',
                'address' => 'Buddha Colony, Kankarbagh',
                'city' => 'Patna',
                'state' => 'Bihar',
                'postal_code' => '800020',
                'country' => 'India',
                'gst_number' => '10AABCP6789R1ZP',
                'license_number' => 'BR-MF-006789',
                'website' => 'https://pharmalink.in',
                'credit_limit' => 200000.00,
                'payment_terms_days' => 30,
                'is_active' => true,
                'notes' => 'Emerging supplier with focus on rural healthcare. Cost-effective solutions for community pharmacies.',
            ],
            // Inactive supplier for testing
            [
                'name' => 'Discontinued Pharma Ltd',
                'code' => 'DISC011',
                'contact_person' => 'Mr. Old Contact',
                'email' => 'old@discontinued.com',
                'phone' => '+91-11-0000-0000',
                'address' => 'Old Address',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'postal_code' => '400001',
                'country' => 'India',
                'gst_number' => '27AABCD0000X1ZO',
                'license_number' => 'MH-MF-000000',
                'credit_limit' => 0.00,
                'payment_terms_days' => 0,
                'is_active' => false,
                'notes' => 'This supplier is no longer active. Historical data maintained for records.',
            ],
        ];

        foreach ($suppliers as $supplierData) {
            Supplier::create($supplierData);
        }

        $this->command->info('Supplier seeder completed successfully!');
        $this->command->info('Created ' . count($suppliers) . ' suppliers');
        $this->command->info('Active suppliers: ' . (count($suppliers) - 1));
        $this->command->info('Inactive suppliers: 1');
    }
}
